'use strict';

/**
 * Broad default target-role keyword list for the Job Intel Pipeline —
 * covers Java/Spring backend, general SDE, frontend/React, full stack,
 * MERN/Node, Python, AI/ML/GenAI, DevOps/Cloud, data engineering, and
 * QA/automation role variants. This is intentionally large; call sites that
 * can only use a handful per run (Adzuna/Jooble cap at 5, LinkedIn Feed at
 * 15) should rotate through it via lib/keywordRotation.js rather than always
 * taking the first N entries, or most of this list would never get used.
 */
module.exports = [
    "Java Developer",
    "Java Backend Developer",
    "Java Backend Engineer",
    "Java Software Engineer",
    "Java Engineer",
    "Java Developer Backend",
    "Java Application Developer",
    "Java Web Developer",
    "Java Programmer",
    "Java Software Developer",
    "Java API Developer",
    "Java Microservices Developer",
    "Java Microservices Engineer",
    "Java Spring Boot Developer",
    "Spring Boot Developer",
    "Spring Boot Engineer",
    "Spring Developer",
    "Spring Framework Developer",
    "Java REST API Developer",
    "Java REST API Engineer",
    "Java Full Stack Developer",
    "Java Full Stack Engineer",
    "Java Enterprise Developer",
    "Java EE Developer",
    "Jakarta EE Developer",
    "J2EE Developer",
    "J2EE Engineer",
    "Java Production Support Engineer",
    "Java Application Support Engineer",
    "Java Technical Consultant",
    "Software Engineer - Java",
    "Software Engineer Java",
    "Software Developer - Java",
    "SDE - Java",
    "SDE 1 - Java",
    "SDE 2 - Java",
    "SDE I - Java",
    "SDE II - Java",
    "Software Development Engineer - Java",
    "Software Development Engineer 1 - Java",
    "Software Development Engineer 2 - Java",
    "Software Engineer I - Java",
    "Software Engineer II - Java",
    "Backend Software Engineer - Java",
    "Backend SDE - Java",
    "Backend SDE 1 - Java",
    "Backend SDE 2 - Java",
    "Associate Software Engineer - Java",
    "Associate Java Developer",
    "Junior Java Developer",
    "Senior Java Developer",
    "Lead Java Developer",
    "Java Technical Lead",
    "Java Architect",
    "Java Solutions Architect",
    "Java Backend Architect",
    "Microservices Developer - Java",
    "Microservices Engineer - Java",
    "Spring Boot Microservices Developer",
    "Java Cloud Developer",
    "Java Cloud Engineer",
    "Java AWS Developer",
    "Java AWS Engineer",
    "Java Azure Developer",
    "Java Azure Engineer",
    "Java GCP Developer",
    "Java GCP Engineer",
    "Java Kubernetes Developer",
    "Java Docker Developer",
    "Java Cloud Native Developer",
    "Java Distributed Systems Engineer",
    "Java Distributed Systems Developer",
    "Java Backend Cloud Engineer",
    "Java SQL Developer",
    "Java MySQL Developer",
    "Java PostgreSQL Developer",
    "Java Oracle Developer",
    "Java Database Developer",
    "Java API Engineer",
    "Java REST Developer",
    "Java RESTful Developer",
    "Java SOAP Developer",
    "Java Hibernate Developer",
    "Java JPA Developer",
    "Java JDBC Developer",
    "Java DevOps Engineer",
    "Java DevOps Developer",
    "Java Cloud DevOps Engineer",
    "Java CI/CD Engineer",
    "Java Jenkins Engineer",
    "Java Docker Engineer",
    "Java Kubernetes Engineer",
    "Java AWS DevOps Engineer",
    "Java Azure DevOps Engineer",
    "Java SRE",
    "Java Site Reliability Engineer",
    "Java Platform Engineer",
    "Java Infrastructure Engineer",
    "Java Release Engineer",
    "Java Build Engineer",
    "Java Automation Engineer",
    "Java AI Engineer",
    "Java AI Developer",
    "Java Machine Learning Engineer",
    "Java ML Engineer",
    "Java AI Software Engineer",
    "Java Generative AI Engineer",
    "Java GenAI Developer",
    "Java AI Application Developer",
    "Java LLM Engineer",
    "Java AI Backend Engineer",
    "Java AI Platform Engineer",
    "Java NLP Engineer",
    "Java Data Engineer - Java",
    "Java + AI Developer",
    "Spring AI Developer",
    "Java AI Integration Engineer",
    "Software Engineer",
    "Software Developer",
    "Software Development Engineer",
    "SDE",
    "SDE 1",
    "SDE 2",
    "SDE I",
    "SDE II",
    "Associate Software Engineer",
    "Junior Software Engineer",
    "Senior Software Engineer",
    "Software Engineer I",
    "Software Engineer II",
    "Software Engineer III",
    "Backend Engineer",
    "Backend Developer",
    "Application Developer",
    "Application Engineer",
    "Platform Engineer",
    "Product Engineer",
    "Systems Engineer",
    "Systems Software Engineer",
    "Application Software Engineer",
    "Software Application Engineer",
    "Software Programmer",
    "Software Development Engineer I",
    "Software Development Engineer II",
    "Backend Software Engineer",
    "Backend Application Developer",
    "API Developer",
    "API Engineer",
    "REST API Developer",
    "REST API Engineer",
    "Microservices Developer",
    "Microservices Engineer",
    "Distributed Systems Engineer",
    "Server Side Developer",
    "Server-Side Engineer",
    "Server Application Developer",
    "Frontend Developer",
    "Frontend Engineer",
    "Front End Developer",
    "Front End Engineer",
    "Frontend Software Engineer",
    "UI Developer",
    "UI Engineer",
    "Web Developer",
    "Web Application Developer",
    "React Developer",
    "React.js Developer",
    "React Engineer",
    "React.js Engineer",
    "React Frontend Developer",
    "React Frontend Engineer",
    "JavaScript Developer",
    "JavaScript Engineer",
    "TypeScript Developer",
    "TypeScript Engineer",
    "Next.js Developer",
    "Next.js Engineer",
    "Angular Developer",
    "Angular Engineer",
    "Vue.js Developer",
    "Vue Developer",
    "HTML CSS JavaScript Developer",
    "UI Software Engineer",
    "Full Stack Developer",
    "Full Stack Engineer",
    "Full-Stack Developer",
    "Full-Stack Engineer",
    "Full Stack Software Engineer",
    "Full Stack Software Developer",
    "Web Full Stack Developer",
    "Full Stack Application Developer",
    "Java React Developer",
    "Java React Full Stack Developer",
    "Java Angular Developer",
    "Java Angular Full Stack Developer",
    "Spring Boot React Developer",
    "Spring Boot Angular Developer",
    "MERN Developer",
    "MERN Stack Developer",
    "MERN Stack Engineer",
    "MERN Full Stack Developer",
    "MERN Full Stack Engineer",
    "MongoDB Express React Node Developer",
    "React Node Developer",
    "React Node.js Developer",
    "Node.js Developer",
    "Node.js Backend Developer",
    "Node.js Engineer",
    "Node Backend Engineer",
    "Express.js Developer",
    "Express.js Backend Developer",
    "MongoDB Developer",
    "Python Developer",
    "Python Backend Developer",
    "Python Software Engineer",
    "Python Engineer",
    "Python Backend Engineer",
    "Python Full Stack Developer",
    "Python Full Stack Engineer",
    "Python API Developer",
    "Python Web Developer",
    "Django Developer",
    "Django Backend Developer",
    "Flask Developer",
    "FastAPI Developer",
    "Python Microservices Developer",
    "Python Cloud Engineer",
    "Python AWS Developer",
    "Python DevOps Engineer",
    "Python Automation Engineer",
    "Python AI Engineer",
    "Python AI Developer",
    "Python Machine Learning Engineer",
    "Python ML Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "AI Software Engineer",
    "AI Developer",
    "Artificial Intelligence Engineer",
    "Generative AI Engineer",
    "GenAI Engineer",
    "GenAI Developer",
    "LLM Engineer",
    "LLM Developer",
    "AI Application Engineer",
    "AI Application Developer",
    "NLP Engineer",
    "Computer Vision Engineer",
    "Deep Learning Engineer",
    "Data Scientist",
    "Python Data Scientist",
    "Data Engineer",
    "Python Data Engineer",
    "ML Software Engineer",
    "ML Software Developer",
    "DevOps Engineer",
    "DevOps Developer",
    "Cloud Engineer",
    "Cloud Software Engineer",
    "Cloud Developer",
    "Cloud DevOps Engineer",
    "AWS Engineer",
    "AWS Developer",
    "AWS Cloud Engineer",
    "Azure Engineer",
    "Azure Developer",
    "Azure Cloud Engineer",
    "GCP Engineer",
    "GCP Developer",
    "Cloud Infrastructure Engineer",
    "Site Reliability Engineer",
    "SRE",
    "Infrastructure Engineer",
    "CI/CD Engineer",
    "DevOps Software Engineer",
    "Release Engineer",
    "Build Engineer",
    "Automation Engineer",
    "Cloud Automation Engineer",
    "Kubernetes Engineer",
    "Docker Engineer",
    "Terraform Engineer",
    "Jenkins Engineer",
    "Software Engineer DevOps",
    "Software Developer DevOps",
    "SDE DevOps",
    "Backend DevOps Engineer",
    "Application DevOps Engineer",
    "Cloud Software Developer",
    "Cloud Application Developer",
    "Cloud Native Developer",
    "Cloud Native Engineer",
    "DevSecOps Engineer",
    "Platform Software Engineer",
    "Infrastructure Software Engineer",
    "Artificial Intelligence Developer",
    "Generative AI Developer",
    "AI/ML Engineer",
    "AI/ML Developer",
    "Machine Learning Developer",
    "ML Engineer",
    "ML Developer",
    "AI Platform Engineer",
    "AI Backend Engineer",
    "AI Software Developer",
    "AI Solutions Engineer",
    "AI Solutions Developer",
    "Software Engineer - Data",
    "Data Software Engineer",
    "Backend Data Engineer",
    "Java Data Engineer",
    "Big Data Engineer",
    "Data Platform Engineer",
    "ETL Developer",
    "ETL Engineer",
    "Data Pipeline Engineer",
    "Analytics Engineer",
    "Cloud Data Engineer",
    "Automation Test Engineer",
    "Software Test Engineer",
    "QA Automation Engineer",
    "SDET",
    "SDET 1",
    "SDET 2",
    "Software Development Engineer in Test",
    "Java Automation Tester",
    "Java SDET",
    "Test Automation Developer",
    "Technical Software Engineer",
    "Technical Engineer",
    "Technology Engineer",
    "IT Software Engineer",
    "Software Consultant",
    "Technical Consultant",
    "Application Support Engineer",
    "Production Support Engineer",
    "Integration Engineer",
    "Integration Developer",
    "API Integration Engineer",
    "Solutions Engineer",
    "Solutions Developer"
];
